### ISSUE TITLE
Store room keys copy in "My notes" 

### ISSUE THREAD

**Issue by buckitupnet** [Buckitup-chat/chat#126]
Encountered during testing - user easily relies  on the keyring backup even when it is made before he joins some rooms. Therefore after the logout the access is lost.  Can we store the room keys in users notes (explicitly & implicitly) for both users convenience and understanding?

**Comment by sergey-lukianov** [comment]
Every room key upon accepting key or room creation should be saved in `My notes` (dialog to myself) as Room invite.
This way having user Identity key is enough to get into rooms he has.

**Comment by sergey-lukianov** [comment]
Tracking amount of room keys unsaved is in #92
