### ISSUE TITLE
accomplish the uploader (frontend)

### ISSUE THREAD

**Issue by buckitupnet** [Buckitup-chat/chat#142]
- the positioning of the uploader must be at the bottom of the screen and not going above roughly the center (scroll helps)
- the files in the uploader that belong to the room have a difference in the background (room background visible in corresponding lines)
- the "paperclip" needs extra signification to appear when something is going on in the uploader (upload is in progress). 
- In desktop the uploader has to fit the sidebar in width

**Comment by sergey-lukianov** [comment]
@Rus9688  please check

**Comment by buckitupnet** [comment]
only the paper clip signification is missing which is quite a minor improvement and is not urgent at all
