### ISSUE TITLE
Cargo checkpoints list

### ISSUE THREAD

**Issue by buckitupnet** [Buckitup-chat/chat#227]
Admin panel need the new vidget for generating the invite-list, just one for the platform like the admins list.
Users may be added or removed to/from the cargo-list  by the Admin
When the Cargo scenario is active (switch in the Admin room is enabled) an option for creating a cargo room is available in the UI (see below)
When cargo room is created, invites automatically sent to all contacts in the cargo list.

The cargo sync performed - the dedicated room is synced, and all the dialogues of the users from **cargo-list** are, synced.

**Comment by buckitupnet** [comment]
Proposal:

- when cargo-sync is activated in Admins room -> no repeating names are allowed for rooms.
- cargo room is created normally just like any other room (given it's name must be unique) 
- any room may be triggers to become cargo room (for some limited time ~2 minutes) this can be canceled.
- in that case the invites are being send to all users on cargo-list, and the room becomes synced with this invites on the dedicated flash-drive, after it is plugged (see above)
- before it happens, the UI shows a modal dialogue "plug in the empty" flash drive (or "cancel"). platform waits for the cargo drive. If the drive has cargo room (or any other db), or time passes, or canceled by user the cargo room is not created. 
- if empty drive attached, the cargo-room creation completes and and it is assigned to that drive.
- the sync and invites to the list performed.
- when complete modal notification is flipped into "cargo-sync initiated successfully" , "ok".
- when a drive with existing cargo  room is plugged, the separate tab appears with that particular cargo room to be accessed directly.

**Comment by buckitupnet** [comment]
Not closing this one since still the rooms list isn't updated properly upon sync on a new system.

**Comment by almirsarajcic** [comment]
Fixed in https://github.com/Buckitup-chat/chat/pull/292.
