### ISSUE TITLE
Accept all Invites

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#228]
We need a way to accept all room invites quick.

It could be :
1. extra option of room invite message in context menu
2. extra button in invite itself
3. on accepted invite we might have `Go to the room` and `Accept All Other`

@buckitupnet what do you think?

**Comment by buckitupnet** [comment]
I think having the third button on the invite itself - "accepted all" is good. 
And then all the invites must turn "accepted" 
When invite is accepted you are not expected to accept anything else from it  (sounds like a wise haiku :)
