### ISSUE TITLE
Half-uploaded files 

### ISSUE THREAD

**Issue by buckitupnet** [Buckitup-chat/chat#411]
When file is half-uploaded and canceled, second try breaks the workflow.

**Comment by buckitupnet** [comment]
The bug is only observed if platform restarted after the half-upload, before the next upload attempt.

**Comment by sviatosluv** [comment]
@buckitupnet @sergey-lukianov 
Interesting situation. My manual test:
1. Uploading a file and stopping it on 50%(it doesn't matter I guess);
2. Canceling the upload;
3. Restarting the server;
3. Uploading the same file. The progress is saved(50%). And I get this problem -> https://github.com/Buckitup-chat/chat/issues/341.
4. When uploading other files - they are ignored.

**Comment by buckitupnet** [comment]
Exactly what I encountered.
