### ISSUE TITLE
Multiple download. Files only mode

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#65]
We want to introduce downloading multiple files without `zip`ing  them.
As shown in first video here. -https://github.com/Buckitup-chat/chat/pull/61

In case if only images, videos and files are selected. Any other type should trigger zipped download.

**Comment by buckitupnet** [comment]
Is it possible to approve the download just once instead for every single file?

**Comment by almirsarajcic** [comment]
We don't have control of that as it's the browser that's giving you the prompt. Only when we download the archive we can have only one warning, because it's only one file.

https://elixirforum.com/t/best-way-to-send-multiple-files-as-http-response/17768/3
https://stackoverflow.com/a/1041591/920303
