### ISSUE TITLE
Approving requests behaviour tweak

### ISSUE THREAD

**Issue by sergey-lukianov** [Buckitup-chat/chat#74]
Requests approving as well as inviting users in room should yield flash message as confirmation of approving.
Currently we have another modal popping up on each user approve.

Consider:
-  using Phoenix flash messages
-  make them fade out in 3 secs

**Comment by buckitupnet** [comment]
Desired feature - when modal popup on the screen, click/tap in the "empty space" (not on the modal) is equivalent to closing the modal
